version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0
    steps:
      - checkout
      - run: cd cmd/server && go build -race
      - run: cd cmd/client/cli && go build -race
      - run: cd cmd/client/generate-load && go build -race
      - run: cd cmd/client/raw-examples && go build -race

  verify:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0
    steps:
      - checkout
      - run: go vet $(go list ./... | grep -v /vendor/)

  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0
    steps:
      - checkout
      - run: go test -v -race ./...

# define order of job execution
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - verify:
          requires:
            - build
      - test:
          requires:
            - verify